name: Build

on:
  push:
    branches:
      - magothy
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Checkout mavlink-c-library
        uses: actions/checkout@v3
        with:
          repository: magothy/mavlink-c-library
          ssh-key: ${{ secrets.SSH_KEY }}
          path: mavlink-c-library

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install future lxml

      - name: Build
        run: |
          set -x
          ls -lah
          ls -lah mavlink-c-library
          python3 "pymavlink/tools/mavgen.py" -o mavlink-c-library/mavlink --lang C --wire-protocol 2.0 --strict-units message_definitions/v1.0/magothy.xml
          ls -lah mavlink-c-library/mavlink
          cd mavlink-c-library
          git config user.email github@magothyrt.com
          git config user.name github-actions
          git status
          git add -A
          git commit --all --allow-empty -m "autogenerated headers for rev $GITHUB_SHA"
          git status
          git push origin main
